# Generated by Django 4.2.4 on 2023-09-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_tupe',
            new_name='plan_type',
        ),
    ]
